/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.avro.example.kafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Stock extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 333044779765363874L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Stock\",\"namespace\":\"com.avro.example.kafka\",\"fields\":[{\"name\":\"stockCode\",\"type\":\"string\"},{\"name\":\"stockName\",\"type\":\"string\"},{\"name\":\"tradeTime\",\"type\":\"long\"},{\"name\":\"preClosePrice\",\"type\":\"float\"},{\"name\":\"openPrice\",\"type\":\"float\"},{\"name\":\"currentPrice\",\"type\":\"float\"},{\"name\":\"highPrice\",\"type\":\"float\"},{\"name\":\"lowPrice\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Stock> ENCODER =
      new BinaryMessageEncoder<Stock>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Stock> DECODER =
      new BinaryMessageDecoder<Stock>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Stock> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Stock> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Stock>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Stock to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Stock from a ByteBuffer. */
  public static Stock fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence stockCode;
  @Deprecated public CharSequence stockName;
  @Deprecated public long tradeTime;
  @Deprecated public float preClosePrice;
  @Deprecated public float openPrice;
  @Deprecated public float currentPrice;
  @Deprecated public float highPrice;
  @Deprecated public float lowPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Stock() {}

  /**
   * All-args constructor.
   * @param stockCode The new value for stockCode
   * @param stockName The new value for stockName
   * @param tradeTime The new value for tradeTime
   * @param preClosePrice The new value for preClosePrice
   * @param openPrice The new value for openPrice
   * @param currentPrice The new value for currentPrice
   * @param highPrice The new value for highPrice
   * @param lowPrice The new value for lowPrice
   */
  public Stock(CharSequence stockCode, CharSequence stockName, Long tradeTime, Float preClosePrice, Float openPrice, Float currentPrice, Float highPrice, Float lowPrice) {
    this.stockCode = stockCode;
    this.stockName = stockName;
    this.tradeTime = tradeTime;
    this.preClosePrice = preClosePrice;
    this.openPrice = openPrice;
    this.currentPrice = currentPrice;
    this.highPrice = highPrice;
    this.lowPrice = lowPrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return stockCode;
    case 1: return stockName;
    case 2: return tradeTime;
    case 3: return preClosePrice;
    case 4: return openPrice;
    case 5: return currentPrice;
    case 6: return highPrice;
    case 7: return lowPrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: stockCode = (CharSequence)value$; break;
    case 1: stockName = (CharSequence)value$; break;
    case 2: tradeTime = (Long)value$; break;
    case 3: preClosePrice = (Float)value$; break;
    case 4: openPrice = (Float)value$; break;
    case 5: currentPrice = (Float)value$; break;
    case 6: highPrice = (Float)value$; break;
    case 7: lowPrice = (Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stockCode' field.
   * @return The value of the 'stockCode' field.
   */
  public CharSequence getStockCode() {
    return stockCode;
  }

  /**
   * Sets the value of the 'stockCode' field.
   * @param value the value to set.
   */
  public void setStockCode(CharSequence value) {
    this.stockCode = value;
  }

  /**
   * Gets the value of the 'stockName' field.
   * @return The value of the 'stockName' field.
   */
  public CharSequence getStockName() {
    return stockName;
  }

  /**
   * Sets the value of the 'stockName' field.
   * @param value the value to set.
   */
  public void setStockName(CharSequence value) {
    this.stockName = value;
  }

  /**
   * Gets the value of the 'tradeTime' field.
   * @return The value of the 'tradeTime' field.
   */
  public Long getTradeTime() {
    return tradeTime;
  }

  /**
   * Sets the value of the 'tradeTime' field.
   * @param value the value to set.
   */
  public void setTradeTime(Long value) {
    this.tradeTime = value;
  }

  /**
   * Gets the value of the 'preClosePrice' field.
   * @return The value of the 'preClosePrice' field.
   */
  public Float getPreClosePrice() {
    return preClosePrice;
  }

  /**
   * Sets the value of the 'preClosePrice' field.
   * @param value the value to set.
   */
  public void setPreClosePrice(Float value) {
    this.preClosePrice = value;
  }

  /**
   * Gets the value of the 'openPrice' field.
   * @return The value of the 'openPrice' field.
   */
  public Float getOpenPrice() {
    return openPrice;
  }

  /**
   * Sets the value of the 'openPrice' field.
   * @param value the value to set.
   */
  public void setOpenPrice(Float value) {
    this.openPrice = value;
  }

  /**
   * Gets the value of the 'currentPrice' field.
   * @return The value of the 'currentPrice' field.
   */
  public Float getCurrentPrice() {
    return currentPrice;
  }

  /**
   * Sets the value of the 'currentPrice' field.
   * @param value the value to set.
   */
  public void setCurrentPrice(Float value) {
    this.currentPrice = value;
  }

  /**
   * Gets the value of the 'highPrice' field.
   * @return The value of the 'highPrice' field.
   */
  public Float getHighPrice() {
    return highPrice;
  }

  /**
   * Sets the value of the 'highPrice' field.
   * @param value the value to set.
   */
  public void setHighPrice(Float value) {
    this.highPrice = value;
  }

  /**
   * Gets the value of the 'lowPrice' field.
   * @return The value of the 'lowPrice' field.
   */
  public Float getLowPrice() {
    return lowPrice;
  }

  /**
   * Sets the value of the 'lowPrice' field.
   * @param value the value to set.
   */
  public void setLowPrice(Float value) {
    this.lowPrice = value;
  }

  /**
   * Creates a new Stock RecordBuilder.
   * @return A new Stock RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Stock RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Stock RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Stock RecordBuilder by copying an existing Stock instance.
   * @param other The existing instance to copy.
   * @return A new Stock RecordBuilder
   */
  public static Builder newBuilder(Stock other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Stock instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Stock>
    implements org.apache.avro.data.RecordBuilder<Stock> {

    private CharSequence stockCode;
    private CharSequence stockName;
    private long tradeTime;
    private float preClosePrice;
    private float openPrice;
    private float currentPrice;
    private float highPrice;
    private float lowPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stockCode)) {
        this.stockCode = data().deepCopy(fields()[0].schema(), other.stockCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stockName)) {
        this.stockName = data().deepCopy(fields()[1].schema(), other.stockName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tradeTime)) {
        this.tradeTime = data().deepCopy(fields()[2].schema(), other.tradeTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.preClosePrice)) {
        this.preClosePrice = data().deepCopy(fields()[3].schema(), other.preClosePrice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[4].schema(), other.openPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.currentPrice)) {
        this.currentPrice = data().deepCopy(fields()[5].schema(), other.currentPrice);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[6].schema(), other.highPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[7].schema(), other.lowPrice);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Stock instance
     * @param other The existing instance to copy.
     */
    private Builder(Stock other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.stockCode)) {
        this.stockCode = data().deepCopy(fields()[0].schema(), other.stockCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stockName)) {
        this.stockName = data().deepCopy(fields()[1].schema(), other.stockName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tradeTime)) {
        this.tradeTime = data().deepCopy(fields()[2].schema(), other.tradeTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.preClosePrice)) {
        this.preClosePrice = data().deepCopy(fields()[3].schema(), other.preClosePrice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[4].schema(), other.openPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.currentPrice)) {
        this.currentPrice = data().deepCopy(fields()[5].schema(), other.currentPrice);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[6].schema(), other.highPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[7].schema(), other.lowPrice);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'stockCode' field.
      * @return The value.
      */
    public CharSequence getStockCode() {
      return stockCode;
    }

    /**
      * Sets the value of the 'stockCode' field.
      * @param value The value of 'stockCode'.
      * @return This builder.
      */
    public Builder setStockCode(CharSequence value) {
      validate(fields()[0], value);
      this.stockCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stockCode' field has been set.
      * @return True if the 'stockCode' field has been set, false otherwise.
      */
    public boolean hasStockCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stockCode' field.
      * @return This builder.
      */
    public Builder clearStockCode() {
      stockCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'stockName' field.
      * @return The value.
      */
    public CharSequence getStockName() {
      return stockName;
    }

    /**
      * Sets the value of the 'stockName' field.
      * @param value The value of 'stockName'.
      * @return This builder.
      */
    public Builder setStockName(CharSequence value) {
      validate(fields()[1], value);
      this.stockName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'stockName' field has been set.
      * @return True if the 'stockName' field has been set, false otherwise.
      */
    public boolean hasStockName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'stockName' field.
      * @return This builder.
      */
    public Builder clearStockName() {
      stockName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradeTime' field.
      * @return The value.
      */
    public Long getTradeTime() {
      return tradeTime;
    }

    /**
      * Sets the value of the 'tradeTime' field.
      * @param value The value of 'tradeTime'.
      * @return This builder.
      */
    public Builder setTradeTime(long value) {
      validate(fields()[2], value);
      this.tradeTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeTime' field has been set.
      * @return True if the 'tradeTime' field has been set, false otherwise.
      */
    public boolean hasTradeTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tradeTime' field.
      * @return This builder.
      */
    public Builder clearTradeTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'preClosePrice' field.
      * @return The value.
      */
    public Float getPreClosePrice() {
      return preClosePrice;
    }

    /**
      * Sets the value of the 'preClosePrice' field.
      * @param value The value of 'preClosePrice'.
      * @return This builder.
      */
    public Builder setPreClosePrice(float value) {
      validate(fields()[3], value);
      this.preClosePrice = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'preClosePrice' field has been set.
      * @return True if the 'preClosePrice' field has been set, false otherwise.
      */
    public boolean hasPreClosePrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'preClosePrice' field.
      * @return This builder.
      */
    public Builder clearPreClosePrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'openPrice' field.
      * @return The value.
      */
    public Float getOpenPrice() {
      return openPrice;
    }

    /**
      * Sets the value of the 'openPrice' field.
      * @param value The value of 'openPrice'.
      * @return This builder.
      */
    public Builder setOpenPrice(float value) {
      validate(fields()[4], value);
      this.openPrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'openPrice' field has been set.
      * @return True if the 'openPrice' field has been set, false otherwise.
      */
    public boolean hasOpenPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'openPrice' field.
      * @return This builder.
      */
    public Builder clearOpenPrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'currentPrice' field.
      * @return The value.
      */
    public Float getCurrentPrice() {
      return currentPrice;
    }

    /**
      * Sets the value of the 'currentPrice' field.
      * @param value The value of 'currentPrice'.
      * @return This builder.
      */
    public Builder setCurrentPrice(float value) {
      validate(fields()[5], value);
      this.currentPrice = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'currentPrice' field has been set.
      * @return True if the 'currentPrice' field has been set, false otherwise.
      */
    public boolean hasCurrentPrice() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'currentPrice' field.
      * @return This builder.
      */
    public Builder clearCurrentPrice() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'highPrice' field.
      * @return The value.
      */
    public Float getHighPrice() {
      return highPrice;
    }

    /**
      * Sets the value of the 'highPrice' field.
      * @param value The value of 'highPrice'.
      * @return This builder.
      */
    public Builder setHighPrice(float value) {
      validate(fields()[6], value);
      this.highPrice = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'highPrice' field has been set.
      * @return True if the 'highPrice' field has been set, false otherwise.
      */
    public boolean hasHighPrice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'highPrice' field.
      * @return This builder.
      */
    public Builder clearHighPrice() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lowPrice' field.
      * @return The value.
      */
    public Float getLowPrice() {
      return lowPrice;
    }

    /**
      * Sets the value of the 'lowPrice' field.
      * @param value The value of 'lowPrice'.
      * @return This builder.
      */
    public Builder setLowPrice(float value) {
      validate(fields()[7], value);
      this.lowPrice = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lowPrice' field has been set.
      * @return True if the 'lowPrice' field has been set, false otherwise.
      */
    public boolean hasLowPrice() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lowPrice' field.
      * @return This builder.
      */
    public Builder clearLowPrice() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Stock build() {
      try {
        Stock record = new Stock();
        record.stockCode = fieldSetFlags()[0] ? this.stockCode : (CharSequence) defaultValue(fields()[0]);
        record.stockName = fieldSetFlags()[1] ? this.stockName : (CharSequence) defaultValue(fields()[1]);
        record.tradeTime = fieldSetFlags()[2] ? this.tradeTime : (Long) defaultValue(fields()[2]);
        record.preClosePrice = fieldSetFlags()[3] ? this.preClosePrice : (Float) defaultValue(fields()[3]);
        record.openPrice = fieldSetFlags()[4] ? this.openPrice : (Float) defaultValue(fields()[4]);
        record.currentPrice = fieldSetFlags()[5] ? this.currentPrice : (Float) defaultValue(fields()[5]);
        record.highPrice = fieldSetFlags()[6] ? this.highPrice : (Float) defaultValue(fields()[6]);
        record.lowPrice = fieldSetFlags()[7] ? this.lowPrice : (Float) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Stock>
    WRITER$ = (org.apache.avro.io.DatumWriter<Stock>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Stock>
    READER$ = (org.apache.avro.io.DatumReader<Stock>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
